version: "3"

services:
  brave:
    image: pog
    #build: .
    network_mode: "host"
    restart: always

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    network_mode: "host"
    depends_on:
      - brave
    restart: always
