version: "3"

services:
  brave:
    image: pog
    #build: .
    ports:
      - "5000:5000"
    restart: always

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
    depends_on:
      - brave
    restart: always
